MODEL:
    NUM_CLASSES: 5
    PRIORS:
      FEATURE_MAPS: [
        [45, 60], [23, 30], [12, 15], [6, 8], [4, 6], [2, 4]
      ]
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [1024, 1024, 1024, 512, 512, 512]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [480, 360]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 8
    LR: 1e-3
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"

TEST:
    BATCH_SIZE: 6
  
EVAL_STEP: 2500
MODEL_SAVE_STEP: 1000