MODEL:
    NUM_CLASSES: 5
    PRIORS:
      FEATURE_MAPS: [
        [45, 60], [23, 30], [12, 15], [6, 8]
      ]
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [1024, 1024, 1024, 1024]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [480, 360]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 10000
    GAMMA: 0.1
    BATCH_SIZE: 12
    LR: 1e-3
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"

TEST:
    BATCH_SIZE: 10

EVAL_STEP: 1000
MODEL_SAVE_STEP: 500