MODEL:
    NUM_CLASSES: 5
    PRIORS:
      FEATURE_MAPS: [
        [30, 40], [15, 20], [8, 10], [1, 1] # [5, 4], [3, 2], [1, 1]
      ]
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [128, 256, 512, 512]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [320, 240]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"