MODEL:
    NUM_CLASSES: 5
    PRIORS:
      FEATURE_MAPS: [
        [30, 40], [15, 20], [8, 10], [4, 5], [2, 3]  # 320x240
        # [45, 60], [23, 30], [12, 15], [6, 8], [3, 4]   # 480x360
        # [90, 120], [45, 60], [23, 30], [12, 15], [6, 8] # 960x720
      ]
      BOXES_PER_LOCATION: [4, 6, 6, 6, 4]
      ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2]]
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [1024, 1024, 1024, 1024, 1024]
        INPUT_CHANNELS: 3

INPUT:
    IMAGE_SIZE: [
      320, 240
      # 480, 360
      # 960, 720
    ]

DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )

SOLVER:
    MAX_ITER: 120000
    # LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
    MOMENTUM: 0.9
    # WEIGHT_DECAY: 0.0001
    WARMUP_FACTOR: 0.25
    WARMUP_ITERS: 100

TEST:
    BATCH_SIZE: 16

OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "datasets"
EVAL_STEP: 500
MODEL_SAVE_STEP: 500
LOG_STEP: 10